name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43e27d755a9643d0ee76170b6c5d106bec5f10ca9f33c94f822c0310315f44dd"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
