name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b4a1404f67a9047633111605b6591523858588bf2a4ba143d6eb1ab9b8c6b2b"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
