name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd546a323fe307f921a8d5bff150ca6fd7a3fab7a75febeb6b6e6015d2cc09c6"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
