name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7798eab356b388445b08ecc548748a56cd55190ca91a53c06e7d2e51b962d7e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
