name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faced0dc6744d916d8c07e91409407ffca83e29926b19834a8492a2f0067ccb6"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
