name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b874987256bd5e8fae131e1cb2dd6b0dd8554ddfa8b298f2217543748801d52"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
