name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05b81698e858d3ca0f0ffe798152c7f31e776a09e51deef0ec243def7c83ccaf"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
