name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab8d94ded81aa9770f700084502cfd0f5f30ae817eb764bfae3116f574f9883d"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
