name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b5a6ef4e6518dc37e12832afd3a0cdb864475d6aa6a034d46f6e99b87db18bd"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
