name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eef7403a42ba95c7912c02fa9fe6d1b0304f42a52ceae37f87bb89a20674408"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
