name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27ac9618f6a3ed2cfdfe3611d62d019eade80acdc22539675c2e990faa63e77b"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
