name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14617a19777d8dbe84dc2a23ec423893157366778dd8379895aee80040cf0bac"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
