name = "Maddy Origins Test Pack Auto-Updated"
author = "Maddy"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2cc3ca8ff72063c4663a653ac393181bc0181bda10c2a6104b8b71cffb2652f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
